# Generated by Django 5.2.17 on 2026-09-14 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productions', '0003_product_slug_productvariantimage_delete_productimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='size',
            name='value',
            field=models.CharField(max_length=50),
        ),
    ]
