# Generated by Django 5.2.17 on 2026-09-14 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productions', '0005_productimage_delete_productvariantimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productimage',
            name='product',
        ),
        migrations.AddField(
            model_name='productvariant',
            name='images',
            field=models.ManyToManyField(blank=True, related_name='variants', to='productions.productimage'),
        ),
    ]
